// AUTO-GENERATED by scripts/generate-media.mjs — do not edit by hand.
// Regenerated on `npm run dev` / `npm run build` (predev / prebuild hooks).

export type GenPost = {
  id: string
  type: 'image' | 'carousel' | 'reel'
  username?: string
  images: string[]
  video_url?: string
  caption: string
  likes_count: number
  comments_count: number
  plays_count?: number
  created_at: string
  aspect_ratio: '1:1' | '4:5' | '1.91:1'
}

export type GenReel = {
  id: string
  username?: string
  video_url: string
  poster_url: string
  caption: string
  audio: string
  likes_count: number
  comments_count: number
  plays_count: number
  created_at: string
}

export const GENERATED_AVAILABLE = true

export const GENERATED_POSTS: GenPost[] = [
  {
    "id": "gen-post-0",
    "type": "carousel",
    "images": [
      "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-00.jpg",
      "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-01.jpg",
      "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-02.jpg",
      "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-03.jpg"
    ],
    "caption": "29 🩷 Registros dos últimos dias celebrando mais um ano de vida e a chegada da Oli",
    "likes_count": 703,
    "comments_count": 88,
    "created_at": "2026-06-17T12:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-1",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/a-celebration-of-our-love-and-our-chosen-home-lo-895cdc-00.mp4",
    "caption": "A celebration of our love and our chosen home London - Our Civil Wedding, 9th May 2026 🥹🤍💍Des",
    "likes_count": 4294,
    "comments_count": 199,
    "plays_count": 50174,
    "created_at": "2026-06-17T11:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-2",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/air-leonie-taking-off-to-paris-for-my-bacheloret-1b1a0a-00.mp4",
    "caption": "Air Leonie taking off to Paris for my Bachelorette- I’m so excited!!! 🥐🇫🇷🛩️🫢🍸👰🏼_♀️💍#bac",
    "likes_count": 7704,
    "comments_count": 149,
    "plays_count": 53584,
    "created_at": "2026-06-17T10:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-3",
    "type": "carousel",
    "images": [
      "/media/feed/animal-print-or-solid-colors-calvinklein-356f47-00.jpg",
      "/media/feed/animal-print-or-solid-colors-calvinklein-356f47-01.jpg"
    ],
    "caption": "animal print or solid colors @calvinklein",
    "likes_count": 4105,
    "comments_count": 110,
    "created_at": "2026-06-17T09:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-4",
    "type": "carousel",
    "images": [
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-00.jpg",
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-01.jpg",
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-02.jpg",
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-03.jpg",
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-04.jpg",
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-05.jpg"
    ],
    "caption": "Anzeige- Lake Como with @guess was so dreamy✨ which one is your fave",
    "likes_count": 4993,
    "comments_count": 218,
    "created_at": "2026-06-17T08:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-5",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/birthday-mornings-with-this-one-ed6667-00.mp4",
    "caption": "birthday mornings with this one 🤍",
    "likes_count": 3193,
    "comments_count": 18,
    "plays_count": 58073,
    "created_at": "2026-06-17T07:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-6",
    "type": "carousel",
    "images": [
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-00.jpg",
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-01.jpg",
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-02.jpg",
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-03.jpg",
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-04.jpg",
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-05.jpg"
    ],
    "caption": "Cannes loading - which one was your fave moment ✨",
    "likes_count": 7008,
    "comments_count": 153,
    "created_at": "2026-06-17T06:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-7",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/come-with-me-into-dior-s-world-los-angeles-here-36ef66-00.mp4",
    "caption": "Come with me into Dior’s world.Los Angeles, here I go.Indo pra Los Angeles conhecer os novos lan",
    "likes_count": 575,
    "comments_count": 160,
    "plays_count": 82455,
    "created_at": "2026-06-17T05:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-8",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/cue-the-slow-clap-df0854-00.mp4",
    "caption": "Cue the slow clap. 👏",
    "likes_count": 3129,
    "comments_count": 74,
    "plays_count": 40009,
    "created_at": "2026-06-17T04:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-9",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/do-you-think-water-has-a-specific-taste-639037-00.mp4",
    "caption": "do you think water has a specific taste",
    "likes_count": 2587,
    "comments_count": 72,
    "plays_count": 30467,
    "created_at": "2026-06-17T03:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-10",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/favorite-nostalgic-candy-5ce797-00.mp4",
    "caption": "favorite nostalgic candy 🍬",
    "likes_count": 6109,
    "comments_count": 34,
    "plays_count": 24989,
    "created_at": "2026-06-17T02:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-11",
    "type": "carousel",
    "images": [
      "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-00.jpg",
      "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-01.jpg",
      "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-02.jpg"
    ],
    "caption": "First time in Budapest and it’s been the best experience @visithungary ✨ Anzeige-Ad Have you bee",
    "likes_count": 8694,
    "comments_count": 179,
    "created_at": "2026-06-17T01:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-12",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-00.mp4",
    "caption": "First time in Budapest and it’s been the best experience @visithungary ✨ Anzeige-Ad Have you bee",
    "likes_count": 8694,
    "comments_count": 179,
    "plays_count": 36574,
    "created_at": "2026-06-17T00:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-13",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/for-dara-and-judson-s-celebration-on-lake-como-t-94a154-00.mp4",
    "caption": "For Dara and Judson’s celebration on Lake Como, they chose the fairytale setting of @villa_balbi",
    "likes_count": 4131,
    "comments_count": 76,
    "plays_count": 23011,
    "created_at": "2026-06-16T23:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-14",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/here-comes-the-christmas-magic-11dbc8-00.mp4",
    "caption": "Here comes the Christmas magic 🎄",
    "likes_count": 5169,
    "comments_count": 94,
    "plays_count": 42049,
    "created_at": "2026-06-16T22:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-15",
    "type": "carousel",
    "images": [
      "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-00.jpg",
      "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-01.jpg",
      "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-02.jpg",
      "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-03.jpg"
    ],
    "caption": "it‘s this time of the year & I couldn‘t be any more excited!! EUROSUMMERRRR!!!!!",
    "likes_count": 8941,
    "comments_count": 6,
    "created_at": "2026-06-16T21:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-16",
    "type": "carousel",
    "images": [
      "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-00.jpg",
      "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-01.jpg",
      "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-02.jpg",
      "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-03.jpg"
    ],
    "caption": "Ladies in red ❤️ Wearing @jacquemus for the @gucci party 🏎️🏁I regret to inform you that I have",
    "likes_count": 3148,
    "comments_count": 133,
    "created_at": "2026-06-16T20:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-17",
    "type": "carousel",
    "images": [
      "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-00.jpg",
      "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-01.jpg",
      "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-02.jpg"
    ],
    "caption": "lost in a summer daydream with @maisonmargielafragrances",
    "likes_count": 8951,
    "comments_count": 156,
    "created_at": "2026-06-16T19:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-18",
    "type": "carousel",
    "images": [
      "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-00.jpg",
      "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-01.jpg",
      "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-02.jpg",
      "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-03.jpg"
    ],
    "caption": "moody day in Lake Como 🤍  #lakecomo",
    "likes_count": 3313,
    "comments_count": 58,
    "created_at": "2026-06-16T18:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-19",
    "type": "carousel",
    "images": [
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-00.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-01.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-02.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-03.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-04.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-05.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-06.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-07.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-08.jpg"
    ],
    "caption": "Oui, oui, baguette ✨🥐🍰So many cute things in my camera roll, I can’t even pick a fave. Okay, m",
    "likes_count": 1736,
    "comments_count": 181,
    "created_at": "2026-06-16T17:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-20",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/our-hearts-are-soooo-full-a9c6a5-00.mp4",
    "caption": "Our hearts are soooo full🥹✨",
    "likes_count": 7810,
    "comments_count": 215,
    "plays_count": 80690,
    "created_at": "2026-06-16T16:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-21",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/packing-away-the-orange-boxes-but-the-memories-a-2eae39-00.mp4",
    "caption": "Packing away the orange boxes,but the memories and stories behind each piece stay forever. A day",
    "likes_count": 4814,
    "comments_count": 179,
    "plays_count": 86694,
    "created_at": "2026-06-16T15:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-22",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/recyclable-dress-fav-dress-ever-usando-marca-bra-a6a59b-00.mp4",
    "caption": "Recyclable dress FAV DRESS EVER Usando marca brasileira @melkzda Vestido feito a partir de garra",
    "likes_count": 7543,
    "comments_count": 68,
    "plays_count": 17423,
    "created_at": "2026-06-16T14:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-23",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/rio-open-x-carnaval-quando-rio-open-e-carnaval-a-3e719f-00.mp4",
    "caption": "Rio Open x Carnaval Quando Rio Open e Carnaval acontecem ao mesmo tempo ❤️Dress @marc_andrade",
    "likes_count": 6783,
    "comments_count": 108,
    "plays_count": 79663,
    "created_at": "2026-06-16T13:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-24",
    "type": "image",
    "images": [
      "/media/feed/riviera-state-of-mind-miumiu-arcadie-anzeige-ad-89abb7-00.jpg"
    ],
    "caption": "Riviera state of mind @MiuMiu Arcadie☕️Anzeige-Ad #MiuMiu #MiuArcadie",
    "likes_count": 5200,
    "comments_count": 65,
    "created_at": "2026-06-16T12:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-25",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/so-are-we-wearing-head-to-toe-red-now-because-sa-a72ec5-00.mp4",
    "caption": "So…are we wearing head-to-toe red now Because, SAME. 💃",
    "likes_count": 4053,
    "comments_count": 178,
    "plays_count": 13933,
    "created_at": "2026-06-16T11:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-26",
    "type": "carousel",
    "images": [
      "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-00.jpg",
      "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-01.jpg",
      "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-02.jpg",
      "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-03.jpg"
    ],
    "caption": "the collection is out!! what’re your favorite pieces🐦_⬛@reformation",
    "likes_count": 524,
    "comments_count": 9,
    "created_at": "2026-06-16T10:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-27",
    "type": "carousel",
    "images": [
      "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-00.jpg",
      "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-01.jpg",
      "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-02.jpg"
    ],
    "caption": "This Halloween We’re dressing up as icons. 📷 @hunterabrams",
    "likes_count": 4957,
    "comments_count": 162,
    "created_at": "2026-06-16T09:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-28",
    "type": "carousel",
    "images": [
      "/media/feed/tuscany-at-the-age-of-love-e247af-00.jpg",
      "/media/feed/tuscany-at-the-age-of-love-e247af-01.jpg",
      "/media/feed/tuscany-at-the-age-of-love-e247af-02.jpg",
      "/media/feed/tuscany-at-the-age-of-love-e247af-03.jpg",
      "/media/feed/tuscany-at-the-age-of-love-e247af-04.jpg"
    ],
    "caption": "Tuscany at the age of love 🌸🍃",
    "likes_count": 1512,
    "comments_count": 17,
    "created_at": "2026-06-16T08:00:00.000Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-29",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/who-had-crushed-up-dry-ramen-as-a-kid-280d68-00.mp4",
    "caption": "who had crushed up dry ramen as a kid😭",
    "likes_count": 1295,
    "comments_count": 180,
    "plays_count": 11175,
    "created_at": "2026-06-16T07:00:00.000Z",
    "aspect_ratio": "4:5"
  }
]

export const GENERATED_REELS: GenReel[] = [
  {
    "id": "gen-reel-1",
    "video_url": "/media/feed/a-celebration-of-our-love-and-our-chosen-home-lo-895cdc-00.mp4",
    "poster_url": "",
    "caption": "A celebration of our love and our chosen home London - Our Civil Wedding, 9th May 2026 🥹🤍💍Des",
    "audio": "Original audio",
    "likes_count": 19674,
    "comments_count": 184,
    "plays_count": 91174,
    "created_at": "2026-06-17T11:00:00.000Z"
  },
  {
    "id": "gen-reel-2",
    "video_url": "/media/feed/air-leonie-taking-off-to-paris-for-my-bacheloret-1b1a0a-00.mp4",
    "poster_url": "",
    "caption": "Air Leonie taking off to Paris for my Bachelorette- I’m so excited!!! 🥐🇫🇷🛩️🫢🍸👰🏼_♀️💍#bac",
    "audio": "Original audio",
    "likes_count": 23084,
    "comments_count": 94,
    "plays_count": 124584,
    "created_at": "2026-06-17T10:00:00.000Z"
  },
  {
    "id": "gen-reel-5",
    "video_url": "/media/feed/birthday-mornings-with-this-one-ed6667-00.mp4",
    "poster_url": "",
    "caption": "birthday mornings with this one 🤍",
    "audio": "Original audio",
    "likes_count": 27573,
    "comments_count": 83,
    "plays_count": 129073,
    "created_at": "2026-06-17T07:00:00.000Z"
  },
  {
    "id": "gen-reel-7",
    "video_url": "/media/feed/come-with-me-into-dior-s-world-los-angeles-here-36ef66-00.mp4",
    "poster_url": "",
    "caption": "Come with me into Dior’s world.Los Angeles, here I go.Indo pra Los Angeles conhecer os novos lan",
    "audio": "Original audio",
    "likes_count": 21955,
    "comments_count": 465,
    "plays_count": 33455,
    "created_at": "2026-06-17T05:00:00.000Z"
  },
  {
    "id": "gen-reel-8",
    "video_url": "/media/feed/cue-the-slow-clap-df0854-00.mp4",
    "poster_url": "",
    "caption": "Cue the slow clap. 👏",
    "audio": "Original audio",
    "likes_count": 9509,
    "comments_count": 19,
    "plays_count": 21009,
    "created_at": "2026-06-17T04:00:00.000Z"
  },
  {
    "id": "gen-reel-9",
    "video_url": "/media/feed/do-you-think-water-has-a-specific-taste-639037-00.mp4",
    "poster_url": "",
    "caption": "do you think water has a specific taste",
    "audio": "Original audio",
    "likes_count": 29967,
    "comments_count": 477,
    "plays_count": 171467,
    "created_at": "2026-06-17T03:00:00.000Z"
  },
  {
    "id": "gen-reel-10",
    "video_url": "/media/feed/favorite-nostalgic-candy-5ce797-00.mp4",
    "poster_url": "",
    "caption": "favorite nostalgic candy 🍬",
    "audio": "Original audio",
    "likes_count": 24489,
    "comments_count": 499,
    "plays_count": 95989,
    "created_at": "2026-06-17T02:00:00.000Z"
  },
  {
    "id": "gen-reel-12",
    "video_url": "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-00.mp4",
    "poster_url": "",
    "caption": "First time in Budapest and it’s been the best experience @visithungary ✨ Anzeige-Ad Have you bee",
    "audio": "Original audio",
    "likes_count": 6074,
    "comments_count": 84,
    "plays_count": 87574,
    "created_at": "2026-06-17T00:00:00.000Z"
  },
  {
    "id": "gen-reel-13",
    "video_url": "/media/feed/for-dara-and-judson-s-celebration-on-lake-como-t-94a154-00.mp4",
    "poster_url": "",
    "caption": "For Dara and Judson’s celebration on Lake Como, they chose the fairytale setting of @villa_balbi",
    "audio": "Original audio",
    "likes_count": 22511,
    "comments_count": 21,
    "plays_count": 44011,
    "created_at": "2026-06-16T23:00:00.000Z"
  },
  {
    "id": "gen-reel-14",
    "video_url": "/media/feed/here-comes-the-christmas-magic-11dbc8-00.mp4",
    "poster_url": "",
    "caption": "Here comes the Christmas magic 🎄",
    "audio": "Original audio",
    "likes_count": 11549,
    "comments_count": 59,
    "plays_count": 153049,
    "created_at": "2026-06-16T22:00:00.000Z"
  },
  {
    "id": "gen-reel-20",
    "video_url": "/media/feed/our-hearts-are-soooo-full-a9c6a5-00.mp4",
    "poster_url": "",
    "caption": "Our hearts are soooo full🥹✨",
    "audio": "Original audio",
    "likes_count": 20190,
    "comments_count": 200,
    "plays_count": 51690,
    "created_at": "2026-06-16T16:00:00.000Z"
  },
  {
    "id": "gen-reel-21",
    "video_url": "/media/feed/packing-away-the-orange-boxes-but-the-memories-a-2eae39-00.mp4",
    "poster_url": "",
    "caption": "Packing away the orange boxes,but the memories and stories behind each piece stay forever. A day",
    "audio": "Original audio",
    "likes_count": 26194,
    "comments_count": 204,
    "plays_count": 37694,
    "created_at": "2026-06-16T15:00:00.000Z"
  },
  {
    "id": "gen-reel-22",
    "video_url": "/media/feed/recyclable-dress-fav-dress-ever-usando-marca-bra-a6a59b-00.mp4",
    "poster_url": "",
    "caption": "Recyclable dress FAV DRESS EVER Usando marca brasileira @melkzda Vestido feito a partir de garra",
    "audio": "Original audio",
    "likes_count": 16923,
    "comments_count": 433,
    "plays_count": 198423,
    "created_at": "2026-06-16T14:00:00.000Z"
  },
  {
    "id": "gen-reel-23",
    "video_url": "/media/feed/rio-open-x-carnaval-quando-rio-open-e-carnaval-a-3e719f-00.mp4",
    "poster_url": "",
    "caption": "Rio Open x Carnaval Quando Rio Open e Carnaval acontecem ao mesmo tempo ❤️Dress @marc_andrade",
    "audio": "Original audio",
    "likes_count": 19163,
    "comments_count": 173,
    "plays_count": 10663,
    "created_at": "2026-06-16T13:00:00.000Z"
  },
  {
    "id": "gen-reel-25",
    "video_url": "/media/feed/so-are-we-wearing-head-to-toe-red-now-because-sa-a72ec5-00.mp4",
    "poster_url": "",
    "caption": "So…are we wearing head-to-toe red now Because, SAME. 💃",
    "audio": "Original audio",
    "likes_count": 13433,
    "comments_count": 443,
    "plays_count": 144933,
    "created_at": "2026-06-16T11:00:00.000Z"
  },
  {
    "id": "gen-reel-29",
    "video_url": "/media/feed/who-had-crushed-up-dry-ramen-as-a-kid-280d68-00.mp4",
    "poster_url": "",
    "caption": "who had crushed up dry ramen as a kid😭",
    "audio": "Original audio",
    "likes_count": 10675,
    "comments_count": 185,
    "plays_count": 72175,
    "created_at": "2026-06-16T07:00:00.000Z"
  }
]

export const MEDIA_IMAGES: string[] = [
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-00.jpg",
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-01.jpg",
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-02.jpg",
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-03.jpg",
  "/media/feed/animal-print-or-solid-colors-calvinklein-356f47-00.jpg",
  "/media/feed/animal-print-or-solid-colors-calvinklein-356f47-01.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-00.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-01.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-02.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-03.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-04.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-05.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-00.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-01.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-02.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-03.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-04.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-05.jpg",
  "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-00.jpg",
  "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-01.jpg",
  "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-02.jpg",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-00.jpg",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-01.jpg",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-02.jpg",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-03.jpg",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-00.jpg",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-01.jpg",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-02.jpg",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-03.jpg",
  "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-00.jpg",
  "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-01.jpg",
  "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-02.jpg",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-00.jpg",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-01.jpg",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-02.jpg",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-03.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-00.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-01.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-02.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-03.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-04.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-05.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-06.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-07.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-08.jpg",
  "/media/feed/riviera-state-of-mind-miumiu-arcadie-anzeige-ad-89abb7-00.jpg",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-00.jpg",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-01.jpg",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-02.jpg",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-03.jpg",
  "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-00.jpg",
  "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-01.jpg",
  "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-02.jpg",
  "/media/feed/tuscany-at-the-age-of-love-e247af-00.jpg",
  "/media/feed/tuscany-at-the-age-of-love-e247af-01.jpg",
  "/media/feed/tuscany-at-the-age-of-love-e247af-02.jpg",
  "/media/feed/tuscany-at-the-age-of-love-e247af-03.jpg",
  "/media/feed/tuscany-at-the-age-of-love-e247af-04.jpg"
]

/** Tiny blurred data-URL placeholder per image url (LQIP). */
export const MEDIA_BLUR: Record<string, string> = {
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-01.jpg": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAABQBQCdASoSABgAPu1qrlCppaQiqAqpMB2JZgCw7ywTo4K6ikXhB1OcoHhPCyphs4SKWUAA+MmHtC0sZHQ5AgAqZ8vzC1+SXTWw/fJoW9+5CmW2YOiAY3Pj82yACFdeuUR235Zm8iW7gSc8bo56qLYGiyp6tTFvVJxqLx5mOG4bjeOkRdgTeKRXbDhudjphSwRepNRGb+ggiNZG6CbCZ8JexG3XU90qZusBGFenByVCWBC2GdrqHkD9J32FnbfOBIAAAA==",
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-02.jpg": "data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAABwBQCdASoSABgAPu1qqFAppaOiqA1RMB2JQBfPUGZjBKqrR7cKRacMyC0Xqv4ySmqrnD9IAP7reTIbxCRQ1D5ZGA1yfYIsLP+eEZ2l9LL7aQN5r5Lx3yTeOZmCFQngcD3iDbFcKDgJMhGaHx91hULSYKFBpSbu6OnvbBAQWajDTicBKZtk2pYAQwXNyCUG1vIURGwlZDM1QC7jKVGkmu4QpnFlfLtZeLHcbxT7g71T4GcrqIhVheMBsQPQSrcdynGlNDGglZA3mBenfE7mdAAA",
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-03.jpg": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAABQBQCdASoSABgAPu1sq1EppaOiqAqpMB2JYgCsEf/ngAEi+7BGk5nzoVowSGnlQ6slNMAA9HJ7XsI5ExdZx9gAiQk1WVDHPbwZV3u/sOSzfD0u1U5lOf86JMtZWnbcaGyTUAhATZbbYMdTWm1cIXlUpeqW2Yt82XE8No497ytACkAG9zNQEuTj0gcE23LImElyVq1FPnripra9J1MKqslDEi2h8dHOc5h/w/2IJP282Rg3AAA=",
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-00.jpg": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACQBQCdASoSABgAPu1qrlCppaQiqAqpMB2JZACdMtU/UBWIarydiSq4viUX5zCiJ79cXnn0AAD+HVSjHMDrN3EYDjSjQN+6nPaJXIhWdr947tuIiXQUWkKC8jlEVRP+UYOrkrg9QlcURVBJ4hWhxN6VR3DPTQoNQbD0P6yQHv5BK7LcwTF+AZXqeLcU8Ha/BisuUUPfC1a3KGLP/PPaS9uSboup+59YrPSrUH8AAAA=",
  "/media/feed/animal-print-or-solid-colors-calvinklein-356f47-01.jpg": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAwBQCdASoSABgAPu1qrlCppaQiqAqpMB2JZQDGQAyyMX38x0f16PleKX75opdXZPTbAAD+vbUiwmya5ST38ebi9oaU+/8f7tDYU8xWIK7FmxApRRjSf8BLtwMgX6Bp0tyccJbTT6rmdcJZQ3YtRWO61RgpuCfGMNFy/B/Pm48XZOqJP5r4uLyM7SkvrWCLteCI7mK91UdDND597qwmGJ00AAA=",
  "/media/feed/animal-print-or-solid-colors-calvinklein-356f47-00.jpg": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAADwBACdASoSABgAPu1ur1IppiQiqAgBMB2JZwDBzd0YPFpXSA6qDQ8Ci1kz5jIsdoAA/uuJ7HPbHhweHSs08Sv2WtP05K9KHAymmaO/EeXs8HbBzCvIz5B7xOZqTxrIT5uq26or48LdehNHlPntCPKgzclMTbHooptfsZhQIcbhFUpm1YHIDOIzFYP3ERfdx94NJk5OKRUxa1dLcSvCN3GxSXcRmYdMfwdkoqD/f0wK1BxfzpenE7rpqe3cm+SRDA+B/OAA",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-01.jpg": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAADwBACdASoSABgAPu1qq1EppaOiqAqpMB2JQBUilvAwnCYx2KLqwq2bGiDqC7TIlqAAzjaW3Bukr5w8yA1kIaxIBrUhHXMV0y99/g+c13gQ6uVn8G31yQJMPsb5RI4LAvSRFY71LDAghgXOjFCJlYB15O2bNbLHHDo58KJmaKBAmreT+PXjZWo7iizc+35HduCVE+XUqgV8+6wsQAK6Pxy+tt3JY40sNpOoqpxU3g6ffT55x9rqRIGgoMAAAA==",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-02.jpg": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADwBACdASoSABgAPu1mrE+ppSQiMBgIATAdiWMAyJgQ7hvdbxYfJft1WB/O6pAJb4AA/upwj7Rg+JrsEREKRgCpWt/2MOIiGgZoNoCgLdo9E5wOUezInpRkUkWkxwtvUu0xelspSpJhqhBwP0spin/uROu+hs+uTuK2UthAc5tLeJhf6TlPj/3yhrTImaJXcPisb9FctNuvAQcMH0UXgAAA",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-03.jpg": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAABQBQCdASoSABgAPu1ur1KppiQiqAgBMB2JYgCw7d0YY3wahIW7QhRgtgAegApn6S7RSMAA/r5VbwnQIaT9XXAJ8/irjkG4E+eFmAI1NhK8PmmXKQIsDJiseTZYb9qnWtYvBW3PczV07hPpQo9yc9Tdq3xfBdqFHTEmWmZLJz0RGMBQhoBdqIOZNk9nuxl2BJgsizCzbYopPWDiVaS4R/jehQRp3LR8LUHK3Y9F+FBk9OXy0TqrJIWQAAA=",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-04.jpg": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAAAQBQCdASoSABgAPu1qrVCppaQiqAqpMB2JQBg5ggRGcn00F0ndKVAn3/eiOJop4x2gAP7Sjy7ju/SoFmjL2+uc40l2GBwt1YF1oJM1AICwL1Re59gfsjUN44xH5zFcJzZNp/aj9r/8nGUcOtJqgHqeQptCClNCa/0NRopL4/Ssi/lzh1mF2Z7bs4Y8D44/Kb1bnqsnqbiwtHra8iH1OFPLDAaZP2L/kXHZm/hD53FrdXaIlzwiTgAA",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-05.jpg": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBQCdASoSABgAPu1kqk4ppaQiMAgBMB2JZQC/7CKUnMUGWOWWVR3qvJOO+pLKzZf7wAD+01AwyU8VsHrSi2lyC5lRL4GZdwGQWjTkJLuexv1jJ0Rk1jIr22Vt76Wr+YxTF9vGsjzlu3WnjUbdumB65EN1USJ3Wa4/HgnKOVAAAA==",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-00.jpg": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAwBQCdASoSABgAPu1iqlAppSOisBgIATAdiUAWI+NnyASaeQidmGP/Qsr2YMMHwX3NAAD93PWttxUB/fgY+71b0vF8U3LRenOYuz5U5t04mXw1YN0/cW3o3Al3fcZec+fhdl8lMdWPSmP98+7Bvq8e3Lbgb62pkANRSZ715+mg7NRWxFbEoTXuNJWTVDVZIAA=",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-01.jpg": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAAAQBQCdASoSABgAPu1kq0+ppSOiMBgIATAdiWMAuzOAgbQvvCLX/zyEPth/GS09YXIAAP7Hr398jXGQ+imHeqh2R7hv9R/EppJj9WEaG6t/Fb+nlPRJDfWvLTedEZ6dL43DrofXTQKKpdlK43cFavpS/X5IJasRzwdz3GN8ENk1T8AlDK5fP8ubcE1S7w2ltVnyMCAQBbOy4EfKS2ZXw5YP8q0FMBt8PcQHfAAA",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-02.jpg": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBACdASoSABgAPu1qqk8ppiOiMBgIATAdiWcAxkAQ3npcx7oi0xqhN1FYAAD+6Oa/Pj6J1Jm6UGzsF7z1tuMB++Rd9q4fypIRBBkHLyh/juZ0Ydz27s/z32k3ev0eebbb32TUSrEq7E9+o9VfbaV0+LFcyHXJhZExD+ucAAA=",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-03.jpg": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAADQBACdASoSABgAPu1ur1IppiQiqAgBMB2JZgAAHgwf1EXM1dCo54f+Q4fvHt3gAAD29VDU00jmT64l1eBcUmmR+J2+Gbwsim5sYuvV2gWZwcfSlp98yVOFDQxZ/nmwCV0yPUpL1nBU0MH/667gMDLbUSha7/WlJ3qrXGF1RXnXoZ0ZoCFlIVAqp3KymV7viqvBnYnxhMJFIuUJ/Cl1pZjfCZ6Y0+jrz8Y2QZSQTSLvPeEnPDVHm26ukf6pgj/3QTH+D6DorHbVwAAA",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-04.jpg": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQBACdASoSABgAPulgo02pJaMiMAwBIB0JZQDGfCHcqoAL38N3Ou+v1XhzGYGsAAD+uVwU/9dfyfaFb2LfIVYkWTx2NH1eFHDbph1I9KOsiAgt5TSLRsmSb4IQUJn6NLDYsS0SsuIk4AKDf+4n+dpWPaQ/MmFRONUwQ5ESgp8/V6ixjBI5CCuAAAA=",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-05.jpg": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAAAwBQCdASoSABgAPu1mp02ppaMiMBgMATAdiWwAAC5xU8h1Bm78ukJITBK3SRAziro+AAD+6OHX3/M8iSTGzAwocHmS2i+hu0Qnn2g8Q0fJn1LpIeUBFkhyaMKy5fl9lgch++0y8bAzt5grqFBLv+NDarsXuBkkGUquy3vyBuo9+eqKJ3c1HCzspZaveW5sm7Ggf227Vz5FFmYwH9X3mhQFIupPhbZWzd745lhKuyg5VMCOYUalpbSxcsXQ32/kt5P0YAAA",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-00.jpg": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAADwBACdASoSABgAPu1mqk8ppaOiKA1RMB2JQBOgAe1u854heIVNxNDQeMYf8zGpgIAA/feluFub50n8lbfqWERgaX6sHPNHeXd2bNQ8EVaYXGs6vIQUTIfk9OITtyo0VbjVZQ/HNfSTZXPK0o1w9euqsj6rxaMmjRaYnkRoPBehVxbY/Hxh256pPCI7+hGCUeY9Ai26bJ9Ow6jplZmx2SYWWwBCMIZHzofhonhzAAA=",
  "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-01.jpg": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAwBQCdASoSABgAPu1oqk8ppiOiKA1RMB2JZAC1CNBA/rS4RQiez66rZklLpBwRE5vgAAD+pqd4cSNud/qcZxVPmBZMqWrA4xVunonmVh7pmxmbow4dwZKG8F5C8SGJo8y01RzlWYBvgW1vXwZWBGxYR1Jx6M8T725CTzEx9IyInKsuGqM6IaPf+bws3BtT+QOzmAzG2GJ54SfWw82h0zRuPjaygAAA",
  "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-02.jpg": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAABwBQCdASoSABgAPu1oq08ppiOiMBgIATAdiWIAsR7fAamq1wwfrV/FnEAq4FcxgLb2I0AAAP7Tacn4wXwcGm4EPNxT+6WnWAPMqxjjkqK37sTDhOYxFk7pe7Rl8atnskhkwiRvdUScfeFXep9zf9+BuJzFcY8BxjcSnfC2BYpzXujUb6iF/7kpQF/CxtVniXoMmEl7WT2Qg5lyVFfeJJPzyewHupT7JGGnHTOxuR/f3tFN2ekrfBMlmNjg/PAA",
  "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-00.jpg": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAADQBQCdASoSABgAPu1mqU2ppaOiMAgBMB2JZQC7IJ26A59VSgBO2gFXPGj2wWUW8aggMCy+QkwAAP7UZt8ugvEtiVrzxFCnGsOdZAA283RjXJDd/1bH98paEpFifCvlsEVI7K0IHyMtNlKEx0F9B8GcTt/wvl2Jr7uZiQRWXDwD1Io149k3DGiU3D33N+RQlBt8/9YckXSBQ9rnaSAe0ErNh00Yo6ePD8nsFvzhnBK2Ov6+6MUOFmSFT10PbJy1oVs3GAAA",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-01.jpg": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADwBACdASoTABgAPu1mq06ppaOiKA1RMB2JZQC7AA0AKa138EJuT95pzxJBxDQjsgAA/uUkyEP7ZnmUWh1DQXxsHjJJNDTQNqYnMfFaYriylTyF3g6Y458T5YKc799WKEYwl6eqtAG8Do31P7kROKyio7QHHmO7HUkylpBTIIZYMCnQLS1rZnkjbZ3hp+yj/i6N7I1xo7qbuKQ7Aniut4vd8Ln3gAAA",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-02.jpg": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABwBACdASoTABgAPu1qq1EppaOiqAqpMB2JZQCzgBGZOWhw32S+Z8sPU4W5sAD+zNZADCeU3AkR821YE3JqP8DxqXwlKiNnbZnHjeBRzKt9tzvDqSuWETAtesIjvKwHzjT7ijnKhY/m0C7vPGGSrO3McM+3MqamK2j0/98n0dmQXKVumFYhwCi1A2io0zZmgwAcOF+mB/L8sHxrtMjKoXHPCapmwAAA",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-03.jpg": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABQBQCdASoTABgAPu1sqE8ppiOiMBgIATAdiWMAuwAPSz80Qgu5WMdb95hf1r98Gj2aPAAA/uc+uEZAvIs/cpmjFeK+m3/BpXREob5UfpXIhGpu4d4Cm80SFpWQ41Zr8eS/dt8Bws3TfDvwQhMBpPmNt+fkDRyNILxCxPdtg3Mc6hYYwGQaONTRN0fgFFAhfoaY+HU4Pf02P7AA",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-00.jpg": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAABwBQCdASoTABgAPu1ur1IppiQiqAgBMB2JYgCdMoS2B6Rgms3bTjEGgYHXVX7OsDdTuv8AAP3um5uw5bZiqUI1xf1RqbfuBs3p9qEzWhUnZ6grRQPh23Wsv16GanWdaQrUFzkCESFz95pWyE222jekXnS5+rJkjK7UYrvXIVPYvirMaLQeg+FazoR0Y/yjRKahjiDmOG0lGr9P9h6iN+KSZ/IPMXD7RsUEAJ+y3EoaAgZgQrAsJQcKfANsj3i75gAAAA==",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-01.jpg": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQBACdASoSABgAPu1osVAppaUiqAqpMB2JZQC/OA6/3sWRpYx4une3nhwAAP7NgwSqPeARPvq3CLxgTSSCGMFP6NQm7MSeRv9OGCByWxGpu3STh+8r3wvq/xVyo+LSRvBSkRu3nJcIRwAA",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-02.jpg": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQBACdASoSABgAPu1iq1AppSOisBgIATAdiWUAygA0b+Ar/F7IXtK8LPAAAP74R2tMigqV8ZoqIVDoWuyVQnEJIvicAa8+k+rqfO0PyOMU0FhyNSptyxaqw7+ZxLFRE60EIAAA",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-03.jpg": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABQBQCdASoSABgAPu1qq08ppiOiMBgIATAdiUATplA1/8A8NeXk5QesPFsjC4Xp8x1QAAAA/qLqwyw9g7H+645H0U3wwxfjTfeowwv2xcxkRlQqMufo5vduH6aKeUK4PGt1gu+nBIY9JUqHyDGuwNlHA67R4eSqd/bhV0c+RnHSJ+1MBg3rp1hfyrFzgYC7sJuDT4bLYDve8//98Fp/1XtzUAA=",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-00.jpg": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAABwBQCdASoSABgAPu1ur1IppiQiqAgBMB2JYgCdIJlBckeOmqT3BLVyU9jePfbS/XxRFfNAAP0hCohTCYsmB7onp66Mxz/nz/xrp1N5ycz37A82mpmJvWAUA1VQWhlN33fuKXpzB2Dpjjt89rg/2cOb1JDpNBHwckhIGOGeNaz0+6F4T/CMCI/3i5GlXOpbT//dBJbV3qBA7JWABoaPLQ6USZsAYtQ0yfA11RuhJDCf6xF1cWwI53AA",
  "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-01.jpg": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQBACdASoTABgAPu1kqE2ppaOiMBgMATAdiWMAtveOgLwHALUxvuOXauaH4HM6wAD+jOp5RoKC3eN9mUdK3vKO7rq2KGiSiy4PC78IPAu8IAJ/+bRCz2YahhlYGHVo6bUkCKdp/UpPxnFlDcHz4Yyr2ngmg+ktVtuaxb4nHEKgAA==",
  "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-02.jpg": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwBACdASoTABgAPu1oqk8ppiOiMBgIATAdiWMAnTMvwYlvH0grFpuLbedcQpsQAPgWstNUpOzxb7sbcjZG+thep3PhUM0TlhL+37Zj/OsffOCod+VA7FV+7cUSLAlGmDo/9HEXX37CHxLRf6lwfwAA",
  "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-00.jpg": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADwBACdASoTABgAPu1qrVCppaQiqAqpMB2JZQCw7Ad3UVCZ2GWM8M3/sNa3K+DiPgAA4mqRAqx1aMlB8ALlHlf/ExVEqhwtxXr+R89lUoUysGYkLsIxT86Y9jXjPGrL4lXdxHdEBHh5SCnEFkpq7ougjrekL5Mb64KlmbIXisUya+lfAFSoAA==",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-01.jpg": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADQBACdASoSABgAPu1gqE2ppSOiMAgBMB2JZQCsACHhcLBMFf3V4BDO3pyD3TNDAAD+52kOYrBAhM4TZ/C3c2PsL5+q63AsItK2oKdBs6SkcScQbrcj8e6Boz6Daduq0JGAqAB4Bjb79t8oF2lL6xu/Lb7faldIyQf6Z6yi0GwdgsS/hMBh0bHbRATj0+yDW5gAAA==",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-02.jpg": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBQCdASoSABgAPu1krU+ppSQiMBgIATAdiWcAsOwRA1rE/46MttJj62P6d7s8h6w50TAAAP5uUQ8tUFPgWz3eFVnNmZzMp0cStIVibS/sPLPEOSYhpo7RvSaJgnurCcsv7VClfvHL/UjxDcVQVrE2ZrAhUuc+ycXbLq1RuPwUdE7Mf+H7osAA",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-03.jpg": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACQBACdASoSABgAPulcp02pJKOiN/VYASAdCWUAuwAQtMmLCcWH+RsWI+vkUFAA/FLDYHvWf+Wjt6RC16oNQFDH5uB9rA8XPcF+YDSkVXGmzEBR8fBQnvhn+m6or6o/yeGC8AfxXIWjTR37qtYC4THO67XuYigJPDwKoxGA1W24ItwAAAA=",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-00.jpg": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBQCdASoSABgAPu1mqU2ppaOiMAgBMB2JYwCxHxgDTq+XVaC45OpByjNWFdWfkf7IAP7eqe6pVpOOr72e2sRdKLCPTBepJjieWVyqkGccqC2ZK7mqmU/tebJjhUYCe/yoWy3cKWCbdOsT87yQfaCQZN9J1OkGQfiL8tIr16Yxp0GPYck2BWPelkTYd1VFGf8FQAAA",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-01.jpg": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAACwBACdASoSABgAPu1sq1EppaOiqAqpMB2JZwDMWA9HeIivaEzw3SCsiTcJ8KkAAP7MEpNpSFMVRS17C/WjRPcR6qktNHeK4bUGbQVqVY3Cs62mSWxmxJCUSBte6biBitToKNDQ1CnZCUS+yN46Vw1xHBfwL1Rna+KBfzBGrW3D68g17F2vznhSg6dTjL784zs/JrVQR+AAAA==",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-02.jpg": "data:image/webp;base64,UklGRuYAAABXRUJQVlA4INoAAACQBQCdASoSABgAPu1sqlEppaOiqAqpMB2JaACnLuAD0CDfYFkIn0Ffcnh/nGGPdDxlKpxzwAD+1tfDmevIgodsz1qaS1uGcPtvqUtlpHbMPo4pkY6iYZgSRQCuKsbGI7PmGxjBXVLWOs4iyeQj3o7naUeI1rTWJB3KsakMEB5gJGrFbjOD/K9Mj2eiHtkzfyVD8RvQCtNnATmO6q3v7Oh9KznP4Wy2+XEzXKR35+m5WosyGE03cMlfRCntpVVAFrMfVczpqKGReQ6Ovw1bsk9RFgeNvDIDEcwAAA==",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-03.jpg": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAABwBQCdASoSABgAPu1sq1EppaOiqAqpMB2JQBOgZYMMALvnntC4jLs7aTGR7QgWobRprXAAAPa239aSux+QKANKswZYJR0lD+qtNNM22RdSnBcqXOsdDC1jnQ/N93xTfs1NexszgFEKoUnkdOGQD8ry23IMwHaq/h0JJHWQlGucsqI8T/2wnN0nGKAHWbC0VjlQIc7uDtKjKO/tmz5JjTxUb2evEsnC0hv1B9uyKGVnsAOohUAAAA==",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-04.jpg": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwBACdASoSABgAPu1sq1EppaOiqAqpMB2JYwC7AAm7c/QgjBTL5M/ylk5IE8W5xAAA+XOCfpuuAqVfFL6nGJmwlsz/WCFbXMyPyblNFx9fDwd/Hfa0Of7U+vXsjlAasvQfKR3R0a8mD+GoURIbDsTMr+bgM20lBFBahAKixmiwaotlzLlaDcEQT7TlI8vekVruYME14uTBjxCLIAA=",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-05.jpg": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABQBQCdASoSABgAPu1mqk2ppaQiMAgBMB2JZQCw/f/gPI8ts/A/EzF7tFd8/QqPe/v/jAAA/uqMazdoZOL+VAgje0+t6zk3VCYh01FG1Bw9Ye9P1yid+xUO/6r6o+YT+hHAMm6/xS/2tznAFUk6T57JmYlGpGhCzFuWOMJR8/38hyx1LXcSh1gNoE6WCyPdAAAAAA==",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-06.jpg": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABwBQCdASoSABgAPu1ep06ppKMiMBgMATAdiWcAwcwQ9RYl35h227UsGUvBCF7JBphNqjwAAP7LO7NjMnAyUYXcYBmdQAdAN8IAHooPE+g/Z801DkEuiRdejZoJSanj9/GqzhtekLclxkn2ZvA0ihKHySfNskIBpjBRei+KdPnU94H4GseVFtyDWNG7UY0NwAAAAA==",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-07.jpg": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABwBACdASoSABgAPu1sqlEppaOiqAqpMB2JZQDE2AxXtU7bNL8ep+4mzbp4AAD+TgTF9OfqEdMKia+A9noaSgvhkafTeCfJzood5DzVKV5+wIqYH5x7N5/OcpO+AjvLK95KaGe2+Dow2rQ+MfUnflxA/xe905YSqITZCXE8JCgAAA==",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-08.jpg": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBQCdASoSABgAPu1iqE2ppaOiMAgBMB2JYwCo9B4YLobLbE37Ctg60CKTlmxI3iiwAP6TgwNOw0eBSo4t49J3vQIZyoQi0IMOuZQ5PzdJpbwPyyzC723t8L7tWQurC9eYT/4047EQDyAl5pd7LzR64X4tWO20TkzI9cr2ZMNQlprVQAA=",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-00.jpg": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQBACdASoSABgAPulkqU2pJaQiMBgMASAdCWUAuwAQ5mXla7qdw2fFWj558+CaoAD+0xESDqoQCMJhHNvCcqwjX3Opc10O1+xlbVcBy90ms4kTMHlQ9CaNW7za3Bin59I02eIJ2vTdkIlNlQnpTZqPMoTnw8DgCI1Skoie3hAAAA==",
  "/media/feed/riviera-state-of-mind-miumiu-arcadie-anzeige-ad-89abb7-00.jpg": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAABwBQCdASoSABgAPu1sq1EppaOiqAqpMB2JZQC4qYzQRJCReMPKIPPHtPVqY6JZhqKq24oAAP7n4gT8eBHVmmt+23ff1Bz57v+5LufzbiyF584g6UqFJgusaSSDI44oevD3ARiq/nr0NuOEuCAjFNUsPtFg+wijnarhBaZbRiPwq+QjYMSnzbQSJDRcRlYPbeMNaZ+W13rbIDmd9oK3zNcN8q4GLKM1+Wh7MUcxKUV1d8qCOr8SIndmCAA=",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-01.jpg": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACQBACdASoSABgAPu1ur1IppiQiqAgBMB2JZwDGfBEc7aUqwmq9e6UVfBVF2w4A/uvoyzJlfsewsJXEZTKZyJhXSupPF/LHzprrnljtSm1GRHqX2esl9sjjPTZOYpy9P59cPytE8sAAAA==",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-02.jpg": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAACwBQCdASoSABgAPu1krE+ppSQiMBgIATAdiUAVhnIN/8AoBT0VbzXsfTR3bQ+/fbmkd5T1iAAA/FpryJlk5LdQb6KHuAfJQ+n6qr3HvaZVB+huo/uzBMBqs4BLSvp3nGYt+JxPksvQfgtSv76XwMCPSkTZz0TNXjMd556MbnYVnzLyHWW1+Xc1KlwjMT5G1VMgnf5vYwyGYbQPMZr44oex1Acw3lWsC+gUsAAA",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-03.jpg": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADwBACdASoSABgAPuFcp02opSOiMAwBEBwJYwC7AdwAswmzmzUz3PNKibxlJyH9vEAA96SF2KZRfSvHD1QLLaSitLVnt/UM6XRYFGbKHajenFiFXFpS2k82HTmw38IGcVGv5HMlZUlM0rT7fk6MvyWFEhFG6ZNwyqLzWfDWx7NEy7MleeEjPUv/T9U87w2dXn8WVjzgsfLDw/ne+DBhi1wA",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-00.jpg": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAQBQCdASoSABgAPu1qrFEppaQiqAqpMB2JZwDM0YyASnusWM4xHDEEuxpEZt39FuiAAPy06gRn7sZvDs5PE6WStpBq6+yLyJhkcK9Axx+knYp1MWuLc6aVz2xnLdy/6AYdI5/xxVzYo6esKimxhbt4xB9tco67aUyGO5rVgKUSjo/1WN/sa1lMuA0rqFHlDD3B+s7pV2dvzkBq1ipX2E3q9u9gAA==",
  "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-01.jpg": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwBACdASoTABgAPu1grFAppSQisBgIATAdiWcAvkgQ31M+VcZwFggZijkXHptQJ1gA/frC/wU4VABQwxMYq0POaITMvTY+rrmicWkclJsPd2C0M3qhCsrhHA0Kj4FWAQv2azw9ktQWrAKkn4vLIvxI9dUkPF7yWMjosglAAAA=",
  "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-02.jpg": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADwBACdASoTABgAPu1qrFEppaQiqAqpMB2JZQCo9Yu4UthAxQ7789ZXd20qSvg+tAAA/mXc6IvT91swHXx+KrYG+LXeIU7JfLM0+Zl5gqVGGUY/WYX6lyJ6CRRjVa57VjJCGJxUrSghSVdTr9WhbnBiiBEZBB17/+nUocVAyBD8R/eJOZsV2tOstKNN7IyGE89B0DSsjgJmkIdC5UmQb2ahZqKe97JGvnE0+AAA",
  "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-00.jpg": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwBACdASoTABgAPuVgpU2pJaOiMAwBIByJQAALxFNvvpKMXk7axk3tcelSIKdgQHgA/lLdh4nYZSnrp0FJfgcAD8/K/F+uOvPj2eL9MQUHBhhI0RGDpHkrFjqGjFwtfgw6fS3FZ74OyAbQjwGjpcTPleFTlc2N42GH4wHJXINoaK/LY2i6K6Wni4JG2nQJ0460Yr5BihYn2uAAAAA=",
  "/media/feed/tuscany-at-the-age-of-love-e247af-01.jpg": "data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAADwBACdASoSABgAPu1ur1KppiQiqAgBMB2JZACuHYw6ZB/7bmmSPTCy4tdc7tKlRUAA/prGccMlTeU01np5L2kVC3GZpjSyeYt1+4Pt5dfAx+7bNphJlb1BpBG8lbkYhdrmwcrCGZixXNJkPRmEW+UL5fORph78Ufson9K6j1vfxJWSxrB3SqGW0giFsfApyK5m+Avb1qFjiSTYSPx9GMV4ONDSKO1oRkCk7qzcNPcCeSqwXHvO3g6WhGFuBemCY3yCNbj0OV5KfjdKWHZdgAAA",
  "/media/feed/tuscany-at-the-age-of-love-e247af-02.jpg": "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAACQBQCdASoSABgAPu1qr1CppaQiqAqpMB2JZgCdMtPzGCXtrf/OxDFEr4zrhdVLVRl9zWhUAAD3w6vlLEPJEOu8zsXEur8JKvC+0PsCIbHoSXoH20B4fdYD5JObYlfLfRMjQuTinWSQSfCs60CPnKibE0OIEiM7WjS98EOe5QD8PGEWQyot8PyGTC+NrdMcUuQ8H2zULaoAcX/a5N25w6osfuf7sFNQ++0bFYXTHrRoDS3cMU4azvKbmWgwRovJbWfqR/ildLEPqIWNJIVzHD5ZYnQgBhAA",
  "/media/feed/tuscany-at-the-age-of-love-e247af-03.jpg": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAAAwBQCdASoSABgAPu1qrlCppaQiqAqpMB2JZADA/JPBg2SAnVC4CCTDnO9cLkSGd+tCgAD+1A8Gc7Wx7Geqn1x3Ac4zPiVGfSFPR8zS3jTIqsUVD1AEYfpKxZcXGFAkKG2pFbCwA04mTzWO2c+xt4AYY1QQCqHIS2bMCZ6EdaTW0/+miWn/AJ/pLlCoSa4cB4Ae/6YHT0WHVaZE0vdW42FOmpcFmtaGniP0AkGxvUiAAA==",
  "/media/feed/tuscany-at-the-age-of-love-e247af-04.jpg": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBQCdASoSABgAPuFeqE2opSQiMAwBEBwJQBdgBDuEQGmFrbfq5Bz63n8/cH32aNAAAPzOStYAHDlgOZQaFvU5scjjSAVpD7DrSiULNDuisaDOZx4hFmE79gko9IyLNFWhXNjs3hRD3P53dnPiM+eYco/4SqeIxPRClrwiMOoosywwmBk9C5RDvzAq4OWK4YhI/BVwbQ8wg/IpAAAAAA==",
  "/media/feed/tuscany-at-the-age-of-love-e247af-00.jpg": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACwBACdASoSABgAPu1oqk+ppiOiMBgIATAdiWYAuwANxONQYWboa9/1522ot4dIAP7UNEm5MRInhIoyZgZfxD3LTW5+aNF/MJFAkQYMrh7AXJ+aKHnD08MN6Ur75+1Q+LsMBVuYPp8iJNiLM6rbLDqWAwz4uYoJAD5yxgrB+aZlyYL3zo/12UBrvnjDoGL6/rSw8ShSaEA5SQEbnqkAAA=="
}
