// AUTO-GENERATED by scripts/generate-media.mjs — do not edit by hand.
// Regenerated on `npm run dev` / `npm run build` (predev / prebuild hooks).

export type GenPost = {
  id: string
  type: 'image' | 'carousel' | 'reel'
  username?: string
  images: string[]
  video_url?: string
  caption: string
  likes_count: number
  comments_count: number
  plays_count?: number
  created_at: string
  aspect_ratio: '1:1' | '4:5' | '1.91:1'
}

export type GenReel = {
  id: string
  username?: string
  video_url: string
  poster_url: string
  caption: string
  audio: string
  likes_count: number
  comments_count: number
  plays_count: number
  created_at: string
}

export const GENERATED_AVAILABLE = true

export const GENERATED_POSTS: GenPost[] = [
  {
    "id": "gen-post-0",
    "type": "carousel",
    "images": [
      "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-00.jpg",
      "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-01.jpg",
      "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-02.jpg",
      "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-03.jpg"
    ],
    "caption": "29 🩷 Registros dos últimos dias celebrando mais um ano de vida e a chegada da Oli",
    "likes_count": 703,
    "comments_count": 88,
    "created_at": "2026-06-16T05:44:23.159Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-1",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/a-celebration-of-our-love-and-our-chosen-home-lo-895cdc-00.mp4",
    "caption": "A celebration of our love and our chosen home London - Our Civil Wedding, 9th May 2026 🥹🤍💍Des",
    "likes_count": 4294,
    "comments_count": 199,
    "plays_count": 50174,
    "created_at": "2026-06-16T04:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-2",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/air-leonie-taking-off-to-paris-for-my-bacheloret-1b1a0a-00.mp4",
    "caption": "Air Leonie taking off to Paris for my Bachelorette- I’m so excited!!! 🥐🇫🇷🛩️🫢🍸👰🏼_♀️💍#bac",
    "likes_count": 7704,
    "comments_count": 149,
    "plays_count": 53584,
    "created_at": "2026-06-16T03:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-3",
    "type": "carousel",
    "images": [
      "/media/feed/animal-print-or-solid-colors-calvinklein-356f47-00.jpg",
      "/media/feed/animal-print-or-solid-colors-calvinklein-356f47-01.jpg"
    ],
    "caption": "animal print or solid colors @calvinklein",
    "likes_count": 4105,
    "comments_count": 110,
    "created_at": "2026-06-16T02:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-4",
    "type": "carousel",
    "images": [
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-00.jpg",
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-01.jpg",
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-02.jpg",
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-03.jpg",
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-04.jpg",
      "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-05.jpg"
    ],
    "caption": "Anzeige- Lake Como with @guess was so dreamy✨ which one is your fave",
    "likes_count": 4993,
    "comments_count": 218,
    "created_at": "2026-06-16T01:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-5",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/birthday-mornings-with-this-one-ed6667-00.mp4",
    "caption": "birthday mornings with this one 🤍",
    "likes_count": 3193,
    "comments_count": 18,
    "plays_count": 58073,
    "created_at": "2026-06-16T00:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-6",
    "type": "carousel",
    "images": [
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-00.jpg",
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-01.jpg",
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-02.jpg",
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-03.jpg",
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-04.jpg",
      "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-05.jpg"
    ],
    "caption": "Cannes loading - which one was your fave moment ✨",
    "likes_count": 7008,
    "comments_count": 153,
    "created_at": "2026-06-15T23:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-7",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/come-with-me-into-dior-s-world-los-angeles-here-36ef66-00.mp4",
    "caption": "Come with me into Dior’s world.Los Angeles, here I go.Indo pra Los Angeles conhecer os novos lan",
    "likes_count": 575,
    "comments_count": 160,
    "plays_count": 82455,
    "created_at": "2026-06-15T22:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-8",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/cue-the-slow-clap-df0854-00.mp4",
    "caption": "Cue the slow clap. 👏",
    "likes_count": 3129,
    "comments_count": 74,
    "plays_count": 40009,
    "created_at": "2026-06-15T21:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-9",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/do-you-think-water-has-a-specific-taste-639037-00.mp4",
    "caption": "do you think water has a specific taste",
    "likes_count": 2587,
    "comments_count": 72,
    "plays_count": 30467,
    "created_at": "2026-06-15T20:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-10",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/favorite-nostalgic-candy-5ce797-00.mp4",
    "caption": "favorite nostalgic candy 🍬",
    "likes_count": 6109,
    "comments_count": 34,
    "plays_count": 24989,
    "created_at": "2026-06-15T19:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-11",
    "type": "carousel",
    "images": [
      "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-00.jpg",
      "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-01.jpg",
      "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-02.jpg"
    ],
    "caption": "First time in Budapest and it’s been the best experience @visithungary ✨ Anzeige-Ad Have you bee",
    "likes_count": 8694,
    "comments_count": 179,
    "created_at": "2026-06-15T18:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-12",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-00.mp4",
    "caption": "First time in Budapest and it’s been the best experience @visithungary ✨ Anzeige-Ad Have you bee",
    "likes_count": 8694,
    "comments_count": 179,
    "plays_count": 36574,
    "created_at": "2026-06-15T17:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-13",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/for-dara-and-judson-s-celebration-on-lake-como-t-94a154-00.mp4",
    "caption": "For Dara and Judson’s celebration on Lake Como, they chose the fairytale setting of @villa_balbi",
    "likes_count": 4131,
    "comments_count": 76,
    "plays_count": 23011,
    "created_at": "2026-06-15T16:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-14",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/here-comes-the-christmas-magic-11dbc8-00.mp4",
    "caption": "Here comes the Christmas magic 🎄",
    "likes_count": 5169,
    "comments_count": 94,
    "plays_count": 42049,
    "created_at": "2026-06-15T15:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-15",
    "type": "carousel",
    "images": [
      "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-00.jpg",
      "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-01.jpg",
      "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-02.jpg",
      "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-03.jpg"
    ],
    "caption": "it‘s this time of the year & I couldn‘t be any more excited!! EUROSUMMERRRR!!!!!",
    "likes_count": 8941,
    "comments_count": 6,
    "created_at": "2026-06-15T14:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-16",
    "type": "carousel",
    "images": [
      "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-00.jpg",
      "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-01.jpg",
      "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-02.jpg",
      "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-03.jpg"
    ],
    "caption": "Ladies in red ❤️ Wearing @jacquemus for the @gucci party 🏎️🏁I regret to inform you that I have",
    "likes_count": 3148,
    "comments_count": 133,
    "created_at": "2026-06-15T13:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-17",
    "type": "carousel",
    "images": [
      "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-00.jpg",
      "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-01.jpg",
      "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-02.jpg"
    ],
    "caption": "lost in a summer daydream with @maisonmargielafragrances",
    "likes_count": 8951,
    "comments_count": 156,
    "created_at": "2026-06-15T12:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-18",
    "type": "carousel",
    "images": [
      "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-00.jpg",
      "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-01.jpg",
      "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-02.jpg",
      "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-03.jpg"
    ],
    "caption": "moody day in Lake Como 🤍  #lakecomo",
    "likes_count": 3313,
    "comments_count": 58,
    "created_at": "2026-06-15T11:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-19",
    "type": "carousel",
    "images": [
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-00.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-01.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-02.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-03.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-04.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-05.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-06.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-07.jpg",
      "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-08.jpg"
    ],
    "caption": "Oui, oui, baguette ✨🥐🍰So many cute things in my camera roll, I can’t even pick a fave. Okay, m",
    "likes_count": 1736,
    "comments_count": 181,
    "created_at": "2026-06-15T10:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-20",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/our-hearts-are-soooo-full-a9c6a5-00.mp4",
    "caption": "Our hearts are soooo full🥹✨",
    "likes_count": 7810,
    "comments_count": 215,
    "plays_count": 80690,
    "created_at": "2026-06-15T09:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-21",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/packing-away-the-orange-boxes-but-the-memories-a-2eae39-00.mp4",
    "caption": "Packing away the orange boxes,but the memories and stories behind each piece stay forever. A day",
    "likes_count": 4814,
    "comments_count": 179,
    "plays_count": 86694,
    "created_at": "2026-06-15T08:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-22",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/recyclable-dress-fav-dress-ever-usando-marca-bra-a6a59b-00.mp4",
    "caption": "Recyclable dress FAV DRESS EVER Usando marca brasileira @melkzda Vestido feito a partir de garra",
    "likes_count": 7543,
    "comments_count": 68,
    "plays_count": 17423,
    "created_at": "2026-06-15T07:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-23",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/rio-open-x-carnaval-quando-rio-open-e-carnaval-a-3e719f-00.mp4",
    "caption": "Rio Open x Carnaval Quando Rio Open e Carnaval acontecem ao mesmo tempo ❤️Dress @marc_andrade",
    "likes_count": 6783,
    "comments_count": 108,
    "plays_count": 79663,
    "created_at": "2026-06-15T06:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-24",
    "type": "image",
    "images": [
      "/media/feed/riviera-state-of-mind-miumiu-arcadie-anzeige-ad-89abb7-00.jpg"
    ],
    "caption": "Riviera state of mind @MiuMiu Arcadie☕️Anzeige-Ad #MiuMiu #MiuArcadie",
    "likes_count": 5200,
    "comments_count": 65,
    "created_at": "2026-06-15T05:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-25",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/so-are-we-wearing-head-to-toe-red-now-because-sa-a72ec5-00.mp4",
    "caption": "So…are we wearing head-to-toe red now Because, SAME. 💃",
    "likes_count": 4053,
    "comments_count": 178,
    "plays_count": 13933,
    "created_at": "2026-06-15T04:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-26",
    "type": "carousel",
    "images": [
      "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-00.jpg",
      "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-01.jpg",
      "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-02.jpg",
      "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-03.jpg"
    ],
    "caption": "the collection is out!! what’re your favorite pieces🐦_⬛@reformation",
    "likes_count": 524,
    "comments_count": 9,
    "created_at": "2026-06-15T03:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-27",
    "type": "carousel",
    "images": [
      "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-00.jpg",
      "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-01.jpg",
      "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-02.jpg"
    ],
    "caption": "This Halloween We’re dressing up as icons. 📷 @hunterabrams",
    "likes_count": 4957,
    "comments_count": 162,
    "created_at": "2026-06-15T02:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-28",
    "type": "carousel",
    "images": [
      "/media/feed/tuscany-at-the-age-of-love-e247af-00.jpg",
      "/media/feed/tuscany-at-the-age-of-love-e247af-01.jpg",
      "/media/feed/tuscany-at-the-age-of-love-e247af-02.jpg",
      "/media/feed/tuscany-at-the-age-of-love-e247af-03.jpg",
      "/media/feed/tuscany-at-the-age-of-love-e247af-04.jpg"
    ],
    "caption": "Tuscany at the age of love 🌸🍃",
    "likes_count": 1512,
    "comments_count": 17,
    "created_at": "2026-06-15T01:44:23.161Z",
    "aspect_ratio": "4:5"
  },
  {
    "id": "gen-post-29",
    "type": "reel",
    "images": [],
    "video_url": "/media/feed/who-had-crushed-up-dry-ramen-as-a-kid-280d68-00.mp4",
    "caption": "who had crushed up dry ramen as a kid😭",
    "likes_count": 1295,
    "comments_count": 180,
    "plays_count": 11175,
    "created_at": "2026-06-15T00:44:23.161Z",
    "aspect_ratio": "4:5"
  }
]

export const GENERATED_REELS: GenReel[] = [
  {
    "id": "gen-reel-1",
    "video_url": "/media/feed/a-celebration-of-our-love-and-our-chosen-home-lo-895cdc-00.mp4",
    "poster_url": "",
    "caption": "A celebration of our love and our chosen home London - Our Civil Wedding, 9th May 2026 🥹🤍💍Des",
    "audio": "Original audio",
    "likes_count": 19674,
    "comments_count": 184,
    "plays_count": 91174,
    "created_at": "2026-06-16T04:44:23.161Z"
  },
  {
    "id": "gen-reel-2",
    "video_url": "/media/feed/air-leonie-taking-off-to-paris-for-my-bacheloret-1b1a0a-00.mp4",
    "poster_url": "",
    "caption": "Air Leonie taking off to Paris for my Bachelorette- I’m so excited!!! 🥐🇫🇷🛩️🫢🍸👰🏼_♀️💍#bac",
    "audio": "Original audio",
    "likes_count": 23084,
    "comments_count": 94,
    "plays_count": 124584,
    "created_at": "2026-06-16T03:44:23.161Z"
  },
  {
    "id": "gen-reel-5",
    "video_url": "/media/feed/birthday-mornings-with-this-one-ed6667-00.mp4",
    "poster_url": "",
    "caption": "birthday mornings with this one 🤍",
    "audio": "Original audio",
    "likes_count": 27573,
    "comments_count": 83,
    "plays_count": 129073,
    "created_at": "2026-06-16T00:44:23.161Z"
  },
  {
    "id": "gen-reel-7",
    "video_url": "/media/feed/come-with-me-into-dior-s-world-los-angeles-here-36ef66-00.mp4",
    "poster_url": "",
    "caption": "Come with me into Dior’s world.Los Angeles, here I go.Indo pra Los Angeles conhecer os novos lan",
    "audio": "Original audio",
    "likes_count": 21955,
    "comments_count": 465,
    "plays_count": 33455,
    "created_at": "2026-06-15T22:44:23.161Z"
  },
  {
    "id": "gen-reel-8",
    "video_url": "/media/feed/cue-the-slow-clap-df0854-00.mp4",
    "poster_url": "",
    "caption": "Cue the slow clap. 👏",
    "audio": "Original audio",
    "likes_count": 9509,
    "comments_count": 19,
    "plays_count": 21009,
    "created_at": "2026-06-15T21:44:23.161Z"
  },
  {
    "id": "gen-reel-9",
    "video_url": "/media/feed/do-you-think-water-has-a-specific-taste-639037-00.mp4",
    "poster_url": "",
    "caption": "do you think water has a specific taste",
    "audio": "Original audio",
    "likes_count": 29967,
    "comments_count": 477,
    "plays_count": 171467,
    "created_at": "2026-06-15T20:44:23.161Z"
  },
  {
    "id": "gen-reel-10",
    "video_url": "/media/feed/favorite-nostalgic-candy-5ce797-00.mp4",
    "poster_url": "",
    "caption": "favorite nostalgic candy 🍬",
    "audio": "Original audio",
    "likes_count": 24489,
    "comments_count": 499,
    "plays_count": 95989,
    "created_at": "2026-06-15T19:44:23.161Z"
  },
  {
    "id": "gen-reel-12",
    "video_url": "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-00.mp4",
    "poster_url": "",
    "caption": "First time in Budapest and it’s been the best experience @visithungary ✨ Anzeige-Ad Have you bee",
    "audio": "Original audio",
    "likes_count": 6074,
    "comments_count": 84,
    "plays_count": 87574,
    "created_at": "2026-06-15T17:44:23.161Z"
  },
  {
    "id": "gen-reel-13",
    "video_url": "/media/feed/for-dara-and-judson-s-celebration-on-lake-como-t-94a154-00.mp4",
    "poster_url": "",
    "caption": "For Dara and Judson’s celebration on Lake Como, they chose the fairytale setting of @villa_balbi",
    "audio": "Original audio",
    "likes_count": 22511,
    "comments_count": 21,
    "plays_count": 44011,
    "created_at": "2026-06-15T16:44:23.161Z"
  },
  {
    "id": "gen-reel-14",
    "video_url": "/media/feed/here-comes-the-christmas-magic-11dbc8-00.mp4",
    "poster_url": "",
    "caption": "Here comes the Christmas magic 🎄",
    "audio": "Original audio",
    "likes_count": 11549,
    "comments_count": 59,
    "plays_count": 153049,
    "created_at": "2026-06-15T15:44:23.161Z"
  },
  {
    "id": "gen-reel-20",
    "video_url": "/media/feed/our-hearts-are-soooo-full-a9c6a5-00.mp4",
    "poster_url": "",
    "caption": "Our hearts are soooo full🥹✨",
    "audio": "Original audio",
    "likes_count": 20190,
    "comments_count": 200,
    "plays_count": 51690,
    "created_at": "2026-06-15T09:44:23.161Z"
  },
  {
    "id": "gen-reel-21",
    "video_url": "/media/feed/packing-away-the-orange-boxes-but-the-memories-a-2eae39-00.mp4",
    "poster_url": "",
    "caption": "Packing away the orange boxes,but the memories and stories behind each piece stay forever. A day",
    "audio": "Original audio",
    "likes_count": 26194,
    "comments_count": 204,
    "plays_count": 37694,
    "created_at": "2026-06-15T08:44:23.161Z"
  },
  {
    "id": "gen-reel-22",
    "video_url": "/media/feed/recyclable-dress-fav-dress-ever-usando-marca-bra-a6a59b-00.mp4",
    "poster_url": "",
    "caption": "Recyclable dress FAV DRESS EVER Usando marca brasileira @melkzda Vestido feito a partir de garra",
    "audio": "Original audio",
    "likes_count": 16923,
    "comments_count": 433,
    "plays_count": 198423,
    "created_at": "2026-06-15T07:44:23.161Z"
  },
  {
    "id": "gen-reel-23",
    "video_url": "/media/feed/rio-open-x-carnaval-quando-rio-open-e-carnaval-a-3e719f-00.mp4",
    "poster_url": "",
    "caption": "Rio Open x Carnaval Quando Rio Open e Carnaval acontecem ao mesmo tempo ❤️Dress @marc_andrade",
    "audio": "Original audio",
    "likes_count": 19163,
    "comments_count": 173,
    "plays_count": 10663,
    "created_at": "2026-06-15T06:44:23.161Z"
  },
  {
    "id": "gen-reel-25",
    "video_url": "/media/feed/so-are-we-wearing-head-to-toe-red-now-because-sa-a72ec5-00.mp4",
    "poster_url": "",
    "caption": "So…are we wearing head-to-toe red now Because, SAME. 💃",
    "audio": "Original audio",
    "likes_count": 13433,
    "comments_count": 443,
    "plays_count": 144933,
    "created_at": "2026-06-15T04:44:23.161Z"
  },
  {
    "id": "gen-reel-29",
    "video_url": "/media/feed/who-had-crushed-up-dry-ramen-as-a-kid-280d68-00.mp4",
    "poster_url": "",
    "caption": "who had crushed up dry ramen as a kid😭",
    "audio": "Original audio",
    "likes_count": 10675,
    "comments_count": 185,
    "plays_count": 72175,
    "created_at": "2026-06-15T00:44:23.161Z"
  }
]

export const MEDIA_IMAGES: string[] = [
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-00.jpg",
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-01.jpg",
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-02.jpg",
  "/media/feed/29-registros-dos-ultimos-dias-celebrando-mais-um-37bfcd-03.jpg",
  "/media/feed/animal-print-or-solid-colors-calvinklein-356f47-00.jpg",
  "/media/feed/animal-print-or-solid-colors-calvinklein-356f47-01.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-00.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-01.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-02.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-03.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-04.jpg",
  "/media/feed/anzeige-lake-como-with-guess-was-so-dreamy-which-9953b5-05.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-00.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-01.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-02.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-03.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-04.jpg",
  "/media/feed/cannes-loading-which-one-was-your-fave-moment-88d973-05.jpg",
  "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-00.jpg",
  "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-01.jpg",
  "/media/feed/first-time-in-budapest-and-it-s-been-the-best-ex-0462d1-02.jpg",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-00.jpg",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-01.jpg",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-02.jpg",
  "/media/feed/it-s-this-time-of-the-year-i-couldn-t-be-any-mor-2caa9c-03.jpg",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-00.jpg",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-01.jpg",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-02.jpg",
  "/media/feed/ladies-in-red-wearing-jacquemus-for-the-gucci-pa-c807db-03.jpg",
  "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-00.jpg",
  "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-01.jpg",
  "/media/feed/lost-in-a-summer-daydream-with-maisonmargielafra-3152f0-02.jpg",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-00.jpg",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-01.jpg",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-02.jpg",
  "/media/feed/moody-day-in-lake-como-lakecomo-fa1089-03.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-00.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-01.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-02.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-03.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-04.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-05.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-06.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-07.jpg",
  "/media/feed/oui-oui-baguette-so-many-cute-things-in-my-camer-c289e4-08.jpg",
  "/media/feed/riviera-state-of-mind-miumiu-arcadie-anzeige-ad-89abb7-00.jpg",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-00.jpg",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-01.jpg",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-02.jpg",
  "/media/feed/the-collection-is-out-what-re-your-favorite-piec-8029a0-03.jpg",
  "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-00.jpg",
  "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-01.jpg",
  "/media/feed/this-halloween-we-re-dressing-up-as-icons-hunter-91e72c-02.jpg",
  "/media/feed/tuscany-at-the-age-of-love-e247af-00.jpg",
  "/media/feed/tuscany-at-the-age-of-love-e247af-01.jpg",
  "/media/feed/tuscany-at-the-age-of-love-e247af-02.jpg",
  "/media/feed/tuscany-at-the-age-of-love-e247af-03.jpg",
  "/media/feed/tuscany-at-the-age-of-love-e247af-04.jpg"
]
